on:
  push:

env:
  VERSION: 1.0.0-g${{ github.sha }}
  DIST_TAG: canary

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com

      - run: npm init --scope ${{ github.repository_owner }} -y

      - run: npm version --no-git-tag-version ${{ env.VERSION }}
      
      - run: npm publish --tag ${{ env.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm dist-tag ls
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install:
    strategy:
      fail-fast: false
      matrix:
        dist-tag: [latest, canary]

    needs: [publish]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com

      - run: npm i @${{ github.repository }}:${{ matrix.dist-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
