on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com

      - run: npm init --scope ${{ github.repository_owner }} -y

      - run: npm version --no-git-tag-version 1.0.0-g${{ github.sha }}
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
